In [2]:
import pandas as pd
import json
import sys
sys.path.append('..')
from scripts import util

In [4]:
conn = util.connect_rds()

In [8]:
sql = 'select * from rws_schema.hectopunten limit 100;'

In [10]:
df = pd.read_sql(sql, con=conn)

In [11]:
df.shape

(100, 296)

In [12]:
df.describe()

,jaar,wvk_id,hectomtrng,afstand,jte_id_beg,jte_id_end,gme_id,endafstand,distrcode,weerstation,...,geleiderails_count,kantobjecten_count,kerngis_groen_count,kerngis_water_count,trees_within50m,trees_within100m,trees_within200m,trees_within300m,trees_within400m,trees_within500m
count,100.0,1.000000e+02,100.00000,100.000000,1.000000e+02,1.000000e+02,100.000000,100.000000,100.000000,100.00000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,2018.0,3.584120e+08,686.50000,442.440000,3.584121e+08,3.606819e+08,864.800000,1398.750000,170.110000,263.43000,...,3.220000,21.070000,1.230000,0.160000,1.600000,8.370000,41.240000,97.790000,148.920000,188.370000
std,0.0,7.761763e+07,468.70366,484.728547,7.761764e+07,7.733843e+07,880.081814,1459.886168,12.770622,18.52994,...,4.414348,21.115486,1.503229,0.677488,6.704438,19.383767,59.151598,112.032399,145.047654,172.794539
min,2018.0,2.613650e+08,100.00000,0.000000,2.613650e+08,2.603650e+08,150.000000,108.000000,159.000000,240.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2018.0,2.613650e+08,104.00000,104.750000,2.613651e+08,2.643640e+08,150.000000,549.000000,160.000000,240.00000,...,0.000000,1.750000,0.000000,0.000000,0.000000,0.000000,0.000000,10.750000,30.750000,42.500000
50%,2018.0,4.173430e+08,1045.00000,296.000000,4.173430e+08,4.193441e+08,150.000000,902.000000,160.000000,278.00000,...,2.000000,16.000000,1.000000,0.000000,0.000000,0.000000,16.500000,33.000000,46.500000,54.000000
75%,2018.0,4.193440e+08,1054.00000,604.750000,4.193441e+08,4.233441e+08,1942.000000,1485.000000,186.000000,278.00000,...,4.000000,31.000000,2.000000,0.000000,0.000000,1.000000,66.000000,138.000000,250.000000,330.250000
max,2018.0,4.623550e+08,1282.00000,3573.000000,4.623550e+08,4.633550e+08,1942.000000,5743.000000,186.000000,283.00000,...,20.000000,81.000000,6.000000,5.000000,48.000000,87.000000,256.000000,452.000000,539.000000,595.000000